CREATE SEQUENCE PEOPLE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE people  (
    person_id NUMBER(10) PRIMARY KEY,
    first_name VARCHAR2(20),
    last_name VARCHAR2(20)
);
CREATE TABLE hospital  (
    rnum NUMBER(10) PRIMARY KEY,
    duty_name VARCHAR2(500)
);